stages:
    - build

build_package:
  stage: build
  image: registry.windmaker.net:5005/a-castellano/limani/base_deb_golang_1_17_builder:202112131727
  script:
    - dpkg-buildpackage -uc -b
    - mkdir deb_package
    - ls -lahrt
    - mv *.deb deb_package/
  artifacts:
    name: "coverage-$CI_PIPELINE_ID"
    paths:
      - deb_package
    expire_in: 1 hour
