stages:
    - build

build_debian_package:
  stage: build
  image: registry.windmaker.net:5005/a-castellano/limani/base_golang_1_22:202407020557
  script:
    - dpkg-buildpackage -uc -b
    - mkdir deb_package
    - mv ../*.deb deb_package/
  artifacts:
    name: "coverage-$CI_PIPELINE_ID"
    paths:
      - deb_package
    expire_in: 1 hour

build_pacman_package:
  stage: build
  image: registry.windmaker.net:5005/a-castellano/limani/base_golang_1_22:202407020557
  script:
    - make build
    - nfpm package --packager archlinux
    - mkdir pacman_package
    - mv *.pkg.tar.zst pacman_package/
  artifacts:
    name: "coverage-$CI_PIPELINE_ID"
    paths:
      - pacman_package
    expire_in: 1 hour
