#!/bin/bash -
#===============================================================================
#
#          FILE: windmaker-infiniterecorder-video-manager
#
#         USAGE: Manage infinite recorder videos
#
#   DESCRIPTION:
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Álvaro Castellano Vela (alvaro.castellano.vela@gmail.com),
#       CREATED: 06/07/2022 08:06
#      REVISION:  ---
#===============================================================================

source lib/01-log.sh
source lib/02-variable-management.sh
source lib/04-ffmpeg.sh
source lib/06-time-management.sh
source lib/07-merge-utils.sh

###################
###     Main    ###
###################

SCRIPT_NAME="Windmaker InfiniteRecorder Video Manager"

write_log "Starting windmaker-infiniterecorder-video-manager"

if [ -z "${ENV_FILE}" ]; then
	write_log "ENV_FILE variable is not defined, aborting"
	exit 1
fi

if [ ! -f "${ENV_FILE}" ]; then
	write_log "${ENV_FILE} does not exist, aborting script."
	exit 1
else
	source "${ENV_FILE}"
fi

# Check Variables
declare -a required_variables
required_variables=(
	'recording-folder'
	'raw-video-delete-time'
	'reduced-video-delete-time'
	'merged-video-period'
	'webcam-instances'
)

abort_script=false

# Check Required variables

for var in "${required_variables[@]}"; do
	variable=$(echo "${var}" | tr '[:lower:]' '[:upper:]' | tr '-' '_')
	check_required_variable "${variable}"
	defined_variable=$?
	if [ "${defined_variable}" = "0" ]; then
		abort_script=true
	fi
done

if [ "${abort_script}" = true ]; then
	write_log "Aborting execucion"
	exit 1
fi

# Calculate merged video period in seconds
declare -g MERGED_VIDEO_PERIOD_SECONDS
MERGED_VIDEO_PERIOD_SECONDS=$(timestring_to_seconds "${MERGED_VIDEO_PERIOD}")

#####
#
#  Get all days between yesterday and earliest non merged video modification day
#  Caclculate days between that dates
#  For each day:
#     Calculate dates o that day with MERGED_VIDEO_PERIOD_SECONDS as inteval
#     Find videos bewteen intervals
#     Merge videos
#     Modify modifcation time to be the same a latest video from inerval
#

declare -g yesterday_date
yesterday_date=$(date +"%Y-%m-%d" -d "- 1 day")

for webcam_instance in "${WEBCAM_INSTANCES[@]}"; do
	write_log "Cheking videos to merge from webcm ${webcam_instance}"
	cam_folder=$(define_cam_foder "${webcam_instance}")
	if [ "${WEBCAM_INSTANCES_INFO[${webcam_instance}_REDUCED_ONLY]}" = false ]; then
		# Pocess raw folder
		merge_videos_from_folder "${cam_folder}" "raw"
	fi
	# Pocess raw reduced folder
	merge_videos_from_folder "${cam_folder}" "raw_reduced"
	write_log "windmaker-infiniterecorder-video-manager ended"

	if [ "${WEBCAM_INSTANCES_INFO[${webcam_instance}_REDUCED_ONLY]}" = false ]; then
	write_log "Removing raw files older than ${RAW_VIDEO_DELETE_TIME} minutes"
	find "${cam_folder}/raw" -type f -mmin "+${RAW_VIDEO_DELETE_TIME}" -delete
	find "${cam_folder}/merged/raw" -type f -mmin "+${RAW_VIDEO_DELETE_TIME}" -delete
	find "${cam_folder}/merged/raw" -type d -empty -delete
	fi
	write_log "Removing reduced files older than ${RAW_VIDEO_DELETE_TIME} minutes"
	find "${cam_folder}/raw_reduced" -type f -mmin "+${RAW_VIDEO_DELETE_TIME}" -delete
	find "${cam_folder}/merged/raw_reduced" -type f -mmin "+${RAW_VIDEO_DELETE_TIME}" -delete
	find "${cam_folder}/merged/raw_reduced" -type d -empty -delete
done
